name: Windows-RDP-Google

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Download and Install Chrome Remote Desktop
      run: |
        # تحميل وتثبيت أداة جوجل الرسمية على السيرفر
        Invoke-WebRequest -Uri "https://dl.google.com/compiled/chromeremotedesktophost.msi" -OutFile "crd.msi"
        Start-Process msiexec.exe -ArgumentList "/i crd.msi /qn" -Wait

    - name: Configure and Start Host
      shell: cmd
      run: |
        # تشغيل الكود الخاص بك وتعيين الـ PIN الافتراضي (123456) لفتح الجهاز
        "%PROGRAMFILES(X86)%\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AeoWuM_78tC2JCkXF5_wcJX5J96U3zmggEupvBeYxrSrpPALvKyJYWEkpq01vzr4rWuMOQ" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=%COMPUTERNAME% --pin=123456

    - name: Keep Alive
      run: |
        # الإبقاء على السيرفر حيًا لمدة 6 ساعات
        Start-Sleep -Seconds 21600
